from .EndpointsEstudiante import endpointEstudiante
from .EndpointsDepartamento import endpointDepartamento
from .EndpointsMateria import endpointMateria
from .EndpointsInscripcion import endpointInscripcion